[package]
name = "blockchain_in_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rust-crypto = "0.2.36"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
sled = "0.34.7"
